# The name of the app. Must be unique within a project.
name: blog_flask

# The type of the application to build
type: 'python:3.10'

hooks:
  build: |
    # Fail the build if any part fails
    set -e
    # Install poetry
    export PIP_USER=false
    curl -sSL https://install.python-poetry.org | python3 - --version $POETRY_VERSION
    export PIP_USER=true
    # Install dependencies
    poetry install        

# Set properties for poetry
variables:
  env:
    POETRY_VERSION: '1.1.14'
    POETRY_VIRTUALENVS_IN_PROJECT: true
    POETRY_VIRTUALENVS_CREATE: false

# The size of the persistent disk of the application (in MB)
disk: 1024

web:
  upstream:
    # Ensure your app listens on the right socket
    socket_family: unix
  commands:
    # The exact command varies based on the server you use

    # 1) ASGI: daphne
    start: "poetry run daphne app.asgi:application"
    # 2) ASGI: uvicorn
    start: "poetry run gunicorn -k uvicorn.workers.UvicornWorker -w 4 -b unix:$SOCKET app.wsgi:application"
    # 3) ASGI: hypercorn
    start: "poetry run hypercorn app.asgi:application"
    # 4) WSGI: gunicorn
    start: "poetry run gunicorn -w 4 -b unix:$SOCKET app.wsgi:application"